Export-incident-to-file-format-of-choice: Implement exportation of in…
robertrachita/STIX pull request #13
Opened 2022-05-24 23:30 UTC by stefanuntura

- Add form with Select and Submit button elements
- Add OnPost() method
- Add Nuget package (Aspose.Cells)
- Implement incident information exporting into file format of choice
- Add To Do comments for implementation of future/unfinished tasks

2022-05-25 08:56 UTC, robertrachita requested changes

2022-05-25 08:56 UTC, robertrachita commented on Stix/Stix/Pages/Incident.cshtml.cs
> +                filledInFile.Save("D:\\Incidents." + format);
this throws exceptions and crashes if you dont have a D drive, should be changed to allow the user to select where to save

2022-05-26 08:32 UTC, naskodh09 approved these changes

2022-05-26 08:40 UTC, robertrachita approved these changes

2022-05-26 08:40 UTC, merged