Added Index page
robertrachita/STIX pull request #7
Opened 2022-05-16 13:05 UTC by SuperChalupa97

2022-05-16 13:07 UTC, stefanuntura requested changes

2022-05-16 13:07 UTC, stefanuntura commented on Stix/Stix.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Stix", "Stix\Stix.csproj", "{E959D165-A9E4-477F-A556-5C8CBC9BFA2A}"
Change this back

2022-05-16 13:10 UTC, SuperChalupa97 commented on Stix/Stix.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Stix", "Stix\Stix.csproj", "{E959D165-A9E4-477F-A556-5C8CBC9BFA2A}"
no

2022-05-16 13:13 UTC, stefanuntura approved these changes

2022-05-17 10:04 UTC, robertrachita approved these changes

2022-05-17 10:04 UTC, merged